github: [metadata]

remote_theme: dieghernan/chulapa

# A. Site Settings
locale                  :
title                   : JKD Wednesday Night Group
title_separator         :
subtitle                : Preserving and promoting Bruce Lee's art of Jeet Kune Do
description             : The Wednesday Night Group preserves and promotes Bruce Lee's art of Jeet Kune Do.
url                     :
baseurl                 :
repository              : jkdpower/jkdpower.github.io
words_per_minute        :
timezone                : America/Los_Angeles

# SEO
og_image                :
twitter_site            :
author:
  name                  : JKD Wednesday Night Group
  avatar                :
  location              : "Redlands, California"

fa_version              :
fa_kit_code             :
fa_v4_support           :

gtag_id                 :
analytics_id            :

# Search
search:
  provider              : fusejs
  label                 :
  landing_page          :
  maxwords              :
  show_attrib           :

comments:
  provider              :
  disqus_shortname      :

# B. Navigation
navbar:
  style     :
  expand    :
  brand:
    title   : Home
    url     : /
    img     :
  nav:
  - title   : About
    url     : /about/
  - title   : Training
    child   :
      - title : Jeet Kune Do
        url   : /jeet-kune-do/
      - title : Combatives
        url   : /combatives/
      - title : Seminars
        url   : /seminars/
      - title : Classes
        url   : /classes/
  - title   : Schools
    child   :
      - title : Official Instructors
        url   : /official/
      - title : Affiliated Schools
        url   : /affiliated/
  - title   : Media
    child   :
      - title : Articles
        url   : /articles/
      - title : Blog
        url   : /blog/
      - title : Self Defense Blog
        url   : /self-defense-blog/
      - title : Videos
        url   : /videos/
      - title : Gallery
        url   : /gallery/
      - title : Books
        url   : /books/
  - title   : Members
    url     : /members/
  - title   : Contact
    url     : /contact/

footer:
  links:
    - label : Facebook
      icon  : fab fa-facebook
      url   : https://www.facebook.com/jkdwednite
    - label : Instagram
      icon  : fab fa-instagram
      url   : https://www.instagram.com/jkdwednite
    - label : YouTube
      icon  : fab fa-youtube
      url   : https://www.youtube.com/@jkdwednite
    - label : RSS
      icon  : fa fa-rss
      url   : ./atom.xml
  copyright : "© JKD Wednesday Night Group"

# C. Theme Settings
googlefonts:

chulapa-skin:
  highlight     :
  skin          :
  autothemer    : true
  vars          :
    primary     : "lightskyblue"

# D. Jekyll Defaults and Collections
paginate      : 4
paginate_path : "/blog/page:num/"
paginator_maxnum : 3

collections:
  sitepages:
    output    : true
    permalink : /:name/

collections_dir :
permalink       : /:year:month:day_:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout              : "default"
      header_type         : "base"
      include_on_search   : false
      cloudtag_url        : /tags
      cloudcategory_url   : /categories
  -
    scope:
      path: ""
      type: "sitepages"
    values:
      layout              : default
      header_type         : base
      show_author         : false
      include_on_search   : true
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type         : "post"
      include_on_search   : true
      include_on_feed     : true
      show_date           : true
      show_related        : true
      show_bottomnavs     : true
      show_sociallinks    : true
      show_comments       : true
      show_tags           : true
      show_categories     : true
      show_author         : true
      show_breadcrumb     : true
      breadcrumb_list     :
        - label: Blog
          url: /blog/

# XX. Other settings
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - docs/

# Conversion
markdown    : kramdown
highlighter : rouge
lsi         : false
excerpt_separator: "\n\n"
incremental : false

kramdown:
  input           : GFM
  hard_wrap       : false
  auto_ids        : true
  footnote_nr     : 1
  footnote_backlink: '&uarr;'
  entity_output   : as_char
  toc_levels      : 2..6
  smart_quotes    : lsquo,rsquo,ldquo,rdquo
  enable_coderay  : false

sass:
  sass_dir    : _sass
  style       : compressed
  quiet_deps  : true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - mixed-decls
    - function-units
    - abs-percent
